version: '3'

services:
  postgres:
    build: ./db
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_NAME: book-exchange-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: "rmzn-test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "pass-123"
    ports:
        - "16543:80"
    depends_on:
      postgres:
        condition: service_healthy

  book-exchange-app:
    container_name: book-exchange-app
    build: ./
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: book-exchange-db
      DB_USERNAME: postgres
      DB_HOSTNAME: postgres
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy